version: 2
updates:
  - package-ecosystem: npm
    directory: /samples/AspNetCoreReactSample/ClientApp
    schedule:
      interval: weekly
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly