name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 10
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            3.1.x
            6.0.x
      - name: Set up MSBuild
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: Build
        run: |
          dotnet --info
          dotnet build -c Release
      - name: Build Samples
        run: |
          dotnet build samples/AspNetCoreIdentitySample/AspNetCoreIdentitySample.csproj -c Release
          dotnet build samples/AspNetCoreSample/AspNetCoreSample.csproj -c Release
          dotnet build samples/AspNetCoreSingleLogoutSample/AspNetCoreSingleLogoutSample.csproj -c Release
          msbuild samples/OwinSample/OwinSample.csproj -noLogo -verbosity:minimal -restore -p:Configuration=Release
          msbuild samples/OwinSingleLogoutSample/OwinSingleLogoutSample.csproj -noLogo -verbosity:minimal -restore -p:Configuration=Release
      - name: Test
        run: |
          dotnet test --collect:"XPlat Code Coverage"
          dotnet tool restore
          dotnet tool run reportgenerator "-reports:**/coverage.cobertura.xml" "-targetdir:coverlet/reports" "-reporttypes:Cobertura"
      - uses: codecov/codecov-action@v3
        with:
          name: unittests-${{ matrix.os }}
